### ISSUE TITLE
www gives an https error

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright.dev#4]
If I navigate to `www.playwright.dev`, my web browser is unhappy.

**Comment by mxschmitt** [comment]
That sounds like a great workaround: https://stackoverflow.com/questions/54817253/github-pages-https-www-redirect

DNS wouldn't fix it (there is no redirect feature there available), it needs to be a redirect on http level, since GitHub Pages internally references to past domain names, we can abuse that feature to have the www. redirect. 

Otherwise if that doesn't work, we can create another repo called www.playwright.dev with an index.html like that: https://github.com/SinusBot/sinusbot.github.io/blob/master/index.html

**Comment by mxschmitt** [comment]
Seems like its now possible to have at least the docs running on both domains: https://github.blog/changelog/2021-04-08-github-pages-can-now-automatically-secure-the-www-variant-of-your-custom-domain/
